# Generated by Django 5.1.1 on 2024-11-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_pregnancycheckup_lmp_date_ad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gmail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
